# Generated by Django 4.1 on 2022-09-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categorya',
            new_name='category',
        ),
    ]
