# Generated by Django 4.1 on 2022-09-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='products',
            field=models.ManyToManyField(related_name='lists', to='Api.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
