# Generated by Django 4.1 on 2022-09-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
    ]
