# Generated by Django 4.1 on 2022-09-19 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_rename_category_product_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
