# Generated by Django 4.1 on 2022-09-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.CharField(blank=True, default='🤬', max_length=50, null=True),
        ),
    ]
