# Generated by Django 4.1 on 2022-09-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_alter_product_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.CharField(blank=True, default='&#128520;', max_length=50, null=True),
        ),
    ]
