###ver listas
GET http://127.0.0.1:8000/api/lists/

###ver una lista
GET http://127.0.0.1:8000/api/lists/1

###agregar listas
POST http://127.0.0.1:8000/api/lists/
content-type: application/json

{
    "name": "lista a modificar",
    "description": "aaaaaaaaa"
}

###modificar lista
PUT http://127.0.0.1:8000/api/lists/7
content-type: application/json

{
    "name": "Otra lista de prueba",
    "description": "modifique la descripcion con el PUT"
}

###eliminar lista
DELETE http://127.0.0.1:8000/api/lists/5

###TEST
GET http://127.0.0.1:8000/api/test/
